Added RGB565 WiFi Zone Streaming
PPUC/ZeDMD pull request #58
Opened 2024-09-06 22:38 UTC by bartdesign

RGB565 Zone streaming support added, moved all the packet handling stuff in a seperate function that is stored in the internal RAM (IRAM_ATTR) area for faster execution.

2024-09-06 22:41 UTC, bartdesign commented
Can somebody please test this out on a real ZeDMD display? As i have only ESP32 S3's with LCD's. This should be tested and confirmed before merging.

2024-09-07 08:05 UTC, mkalkbrenner requested changes
Just small issues in the code.
But I think the new build target in platformio.ini is missing. Or will that be a new PR?

2024-09-07 08:05 UTC, mkalkbrenner commented on src/main.cpp
> +  int packetLength = packet.length();
This variable is not used.

2024-09-07 08:05 UTC, mkalkbrenner commented on src/main.cpp
> +            debugMode = true;
must be removed

2024-09-07 08:05 UTC, mkalkbrenner commented on src/main.cpp
> +            Serial.println("RGB24-5");
must be removed

2024-09-07 08:05 UTC, mkalkbrenner commented on src/main.cpp
> +            debugMode = true;
must be removed

2024-09-07 08:05 UTC, mkalkbrenner commented on src/main.cpp
> +            Serial.println("RGB565-ERROR");
must be removed

2024-09-07 13:44 UTC, bartdesign commented
I have a hard time fixing my mistakes in git. I'm going to refork and send in a new request.

2024-09-07 13:44 UTC, closed without merging