Lilygo S3 AMOLED Display support, Refractoring and cleanup, S3 Wifi tweaks, new ESP32 framework
PPUC/ZeDMD pull request #62
Opened 2024-09-15 09:40 UTC by bartdesign

## Release Notes:

- **Refactored DisplayDriver**: Created a `DisplayDriver` class and moved existing display-related code into their own respective classes.
- **LilyGo S3 AMOLED Support**: Wi-Fi works well. However, the serial-only version does not work due to current issues affecting all ESP32-S3 models.
- **ESP32-S3 Wi-Fi Performance Tweaks**: Added performance optimizations based on Espressif’s technical documentation.
- **Simplified Espressif32 Framework Downloading**: Included the latest version of the framework, which includes `IRAM_ATTR` optimizations for better performance.

---

## Areas for Improvement:

- **Platform and Config Naming**: I propose introducing a new `#ifdef` for display types and another for ESP32-S3 models, replacing the current `#ifdef ARDUINO_ESP32_S3_N16R8` with a new variable specific to ESP32-S3. This will make the `#ifdef` conditions cleaner and easier to read. If you agree, I can submit a pull request for this change.
- **Fill Methods Refactor**: I had to move the fill methods into the `DisplayDriver` section. Ideally, I would have kept these methods in `main.cpp` and just utilized the pixel-drawing functions, but display-specific implementations were necessary for scaling and text fonts.

---

## Future Improvements:

- **Faster Screen Refresh Techniques**: In theory, the display should be capable of reaching 60 FPS. This can be achieved through various methods, such as sending and receiving full frames. I plan to investigate better techniques, SIMD, and different transmission protocols when I have time.
- **High-Resolution Fonts for High-Resolution Displays**: I will create a pull request to support higher resolution fonts on high-resolution displays.
- **256x64 Pixel Display Support**: This will require faster data transmission and optimized drawing techniques, but it's a planned improvement.

This PR and the previous one need to be thoroughly tested on a real ZeDMD as i only have non standard displays available right now. This PR has been tested on the Lilygo S3 Amoled and a older ESP32WROOM without a display connected via WiFi and Serial.

2024-09-15 21:50 UTC, mkalkbrenner requested changes

2024-09-15 21:50 UTC, mkalkbrenner commented on src/displays/LEDMatrix.cpp
> +/// @brief Draw a RGB888 pixel
All that documentation should be moved to the virtual base class in displayDriver.h

2024-09-15 21:50 UTC, mkalkbrenner commented on src/displays/LEDMatrix.h
> +    virtual void DrawPixel(uint16_t x, uint16_t y, uint8_t r, uint8_t g, uint8_t b) override;
I think that "virtual" and "override" should be removed.

2024-09-15 21:50 UTC, mkalkbrenner commented on src/displays/LilygoS3Amoled.h
> +class LilygoS3Amoled : public DisplayDriver {
Maybe Rm67162Amold is a better name. This code seems to be suitable for other S3 based controllers and that display attached via SPI.

2024-09-15 21:50 UTC, mkalkbrenner commented on src/displayConfig.cpp
> +// I needed to change these from RGB to RC (Red Color), BC, GC to prevent conflicting with the TFT_SPI Library.
Using  a namespace avoids that conflict.
Since we introduce classes now, we should use a ZeDMD namespace.

2024-09-15 21:50 UTC, mkalkbrenner commented on src/displayConfig.h
> +#ifndef DISPLAYCONFIG_H
I think that the entire content of displayConfig.h and displayConfig.cpp should be moved into displayDriver.h

2024-09-15 21:50 UTC, mkalkbrenner commented on src/main.cpp
> +uint8_t lumstep = 10; //Init display on 70% brightness, otherwise it starts up black on some displays
10 is too much if you power over USB. I think 5 is a suitable value. If it isn't enough for the LCD screen, we need a condition here.

2024-09-15 21:50 UTC, mkalkbrenner commented on src/main.cpp
> +DisplayDriver* display;  // Pointer to the base class
It isn't a pointer to the "base class". It is a pointer of that type.

2024-09-15 21:50 UTC, mkalkbrenner commented on src/webserver.cpp
> +      GetDisplayObject()->SetBrightness(lumstep);
If we define the display variable as extern in main.cpp and webserver.h, we can instantiate it in displayDriver.h and don't need GetDisplayObject().

2024-09-15 21:50 UTC, mkalkbrenner commented on src/webserver.cpp
> +      GetDisplayObject()->SetBrightness(lumstep);
On the other hand, we could simply pass display as parameter.

2024-09-16 09:39 UTC, bartdesign commented on src/displays/LEDMatrix.cpp
> +/// @brief Draw a RGB888 pixel
Fixed

2024-09-16 09:46 UTC, bartdesign commented on src/displays/LilygoS3Amoled.h
> +class LilygoS3Amoled : public DisplayDriver {
Changed to Rm67162Amoled. Also i have changed the ifdef to DISPLAY_RM67162_AMOLED.

2024-09-16 09:48 UTC, bartdesign commented on src/main.cpp
> +uint8_t lumstep = 10; //Init display on 70% brightness, otherwise it starts up black on some displays
Fixed.

2024-09-16 09:50 UTC, bartdesign commented on src/webserver.cpp
> +      GetDisplayObject()->SetBrightness(lumstep);
How do you propose we fix it?

2024-09-16 09:53 UTC, bartdesign commented on src/displays/LEDMatrix.h
> +    virtual void DrawPixel(uint16_t x, uint16_t y, uint8_t r, uint8_t g, uint8_t b) override;
Removed.

2024-09-16 10:24 UTC, bartdesign commented on src/displayConfig.h
> +#ifndef DISPLAYCONFIG_H
This has been resolved.

2024-09-16 10:25 UTC, bartdesign commented on src/displayConfig.cpp
> +// I needed to change these from RGB to RC (Red Color), BC, GC to prevent conflicting with the TFT_SPI Library.
I need some help with this one; check my last commit. I put those defines in the ZeDMD namespace. But my compiles are still failing for the same reasons:

`src/displayDriver.h:9:15: error: expected nested-name-specifier before numeric constant
     #define B 2
               ^
.pio/libdeps/LilygoS3Amoled_128x32/TFT_eSPI/TFT_eSPI.h:989:44: note: in expansion of macro 'B'`

2024-09-18 20:59 UTC, ojacques commented on src/main.cpp
> +    WiFi.setSleep(false); // WiFi speed improvement on ESP32 S3 and others.
A huge improvement with this commit on my ZeDMD ESP32 (not S3).
https://www.youtube.com/watch?v=lHKhQKOukA8

2024-10-09 10:04 UTC, merged